---
# Purpose: Check for directory to write out cert files
# Last Updated: 2018.07.23
# Notes:


- name: "drewgwallace.open_ssl_self_signed | Check output directory"
  local_action:
    module: file
    path: "{{ cert_dir }}"
    state: directory